### PR TITLE
feat(charts,logging-operator): make configCheck configurable in loggi…

### PR DESCRIPTION
**Pull request by sebastiangaiser**
…ng resource

I ran into https://github.com/kube-logging/logging-operator/issues/1377 and would like to give it a try.

### CODE REVIEW

**Comment by sebastiangaiser** [comment]
@pepov can you please guide me a bit if this is a minor or patch for you?

**Comment by pepov** [comment]
@sebastiangaiser you don't need other than a release, which will automatically set the chart version as part of the workflow

**Review by pepov — APPROVED** [review]

**Comment by sebastiangaiser** [comment]
Ok, shall I update/rebase my branch from main?

**Comment by pepov** [comment]
not necessary for this

**Review by OverOrion — APPROVED** [review]

**Pull request merged**
