### PR TITLE
deps: upgrade fluentbit to 2.2.2

### PR DESCRIPTION
**Pull request by aslafy-z**
Upgrade [fluentbit to v2.2.2](https://github.com/fluent/fluent-bit/releases/tag/v2.2.2)
Includes https://github.com/fluent/fluent-bit/pull/8129

### CODE REVIEW

**Review by pepov — APPROVED** [review]

**Review by pepov — CHANGES_REQUESTED** [review]
Sorry, I just realized we have a few more places where we use the fluentbit image, let's update those references as well (simply search for 2.1.8)

**Comment by aslafy-z** [comment]
Thanks for the heads up, I will try this at home before making it land in logging-operator!

**Review by pepov — APPROVED** [review]

**Comment by pepov** [comment]
I can take the tailer part if that helps

**Comment by aslafy-z** [comment]
I found an issue similar to https://github.com/fluent/fluent-bit/issues/5003 on this version. Will freeze this upgrade until I get some news from fluentbit maintainers.

**Comment by aslafy-z** [comment]
Ok, looks like it was an issue with my probe configuration. Ready to merge!

**Review by OverOrion — APPROVED** [review]
Thanks @aslafy-z!

**Pull request merged**
