### PR TITLE
Gelf output plugin: improved docs and add missing flags

### PR DESCRIPTION
**Pull request by bmichalkiewicz**
This pull request corrects documentation and adds the missing max_bytes flag (introduced in version 1.3.4 of [fluent-plugin-gelf-best](https://github.com/bmichalkiewicz/fluent-plugin-gelf-best)).

Additionally, the term "GELF" has been changed to "Gelf" in the code for clarity, as there's no reason to capitalize it.

we need to update the gem to version 1.3.4 as it fixes: https://github.com/Graylog2/graylog2-server/issues/873

### CODE REVIEW

**Comment by bmichalkiewicz** [comment]
There should be information about which Fluentd image supports the max_bytes flag, but I don't know it at the moment.
// Available since ghcr.io/kube-logging/fluentd:v1.16-4.8-full

**Comment by pepov** [comment]
@bmichalkiewicz most probably it will be 4.10

**Comment by bmichalkiewicz** [comment]
Thanks for the information :)

**Comment by pepov** [comment]
@bmichalkiewicz would you mind updating the image to v4.10 once https://github.com/kube-logging/fluentd-images/actions/runs/11032457110 has been built?

this is where the image is configured:
https://github.com/kube-logging/logging-operator/blob/184dbc2312189e8658679a7f0fdfd0f293d8e369/pkg/sdk/logging/api/v1beta1/logging_types.go#L181

https://github.com/kube-logging/fluentd-images/pull/146

**Comment by pepov** [comment]
the image has already updated in main, started a rebase

**Review by pepov — APPROVED** [review]

**Pull request merged**
