### PR TITLE
chore: charts up

### PR DESCRIPTION
**Pull request by pepov**
And sync to https://github.com/kube-logging/helm-charts/pull/15

### CODE REVIEW

**Comment by genofire** [comment]
Why still fill https://github.com/kube-logging/helm-charts ? and not make there ci part of this repo?

**Comment by genofire** [comment]
Please also update / explain the different urls in:
https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator/README.md
and
https://github.com/kube-logging/logging-operator/blob/master/charts/logging-operator-logging/README.md

or move `e2e/charts` to `charts`

**Comment by pepov** [comment]
Thanks for the reminder, I've just added notes about this state. I'm not relaxed to move the charts back to their original place until we fix this far from ideal state.

**Comment by pepov** [comment]
> Why still fill https://github.com/kube-logging/helm-charts ? and not make there ci part of this repo?

Because the decision was to use a static helm repo temporarily (to replace the original banzaicloud repo), which requires the  charts to be in the given git repo. We will move the charts back here and implement an OCI based release later, but that requires some more time which we don't have at the very moment.

**Comment by pepov** [comment]
@genofire I've sent you a collaborator invite, so that I can add you on PRs you might be interested in (like this one) as a reviewer from now on

**Pull request merged**
