### PR TITLE
Feat: add PodDisruptionBudget for fluentd

### PR DESCRIPTION
**Pull request by yunkunrao**
This pull request is related with #1520 and add a new pdb field to enhance FluentdSpec.

### CODE REVIEW

**Comment by yunkunrao** [comment]
> Hey @yunkunrao , thanks for the PR!
> 
> It seems to me, that we let the user configure a full `pdb`, but then we overwrite the selector completely. I would suggest to let the user configure the fields that we actually use. What do you think?

You mean we let user themselves to create pdb and our logging controller override the pdb spec. selector field with new selector in fluentd. Well, it makes sense.

**Comment by pepov** [comment]
@yunkunrao no, I meant that by using the poddisruptionbudget type instead of just minUnavailable, maxUnavailable and unhealthyPodEvictionPolicy the user might be confused whether what they should configure as selectors (which they don't have to touch)

**Comment by yunkunrao** [comment]
> @yunkunrao no, I meant that by using the poddisruptionbudget type instead of just minUnavailable, maxUnavailable and unhealthyPodEvictionPolicy the user might be confused what they should configure for selectors (which they don't have to touch)

Got it. Maybe we should only expose just minUnavailable, maxUnavailable and unhealthyPodEvictionPolicy to the user for easy use and avoid misunderstanding.

**Review by pepov — APPROVED** [review]

**Review by OverOrion — APPROVED** [review]

**Comment by pepov** [comment]
thanks @yunkunrao !

**Pull request merged**
