### PR TITLE
breaking: remove sumologic filter and output, enchance_k8s filter

### PR DESCRIPTION
**Pull request by csatib02**
Fixes: #1856

### CODE REVIEW

**Review by pepov — APPROVED** [review]

**Review by pepov — CHANGES_REQUESTED** [review]
can you please update the new image version in this same PR?

**Comment by pepov** [comment]
The new image versions are:
`v1.17-v5.0-full` and `v1.17-v5.0-base` for the e2e tests

**Comment by csatib02** [comment]
@pepov Bumped the images in the latest commit.

**Comment by pepov** [comment]
The second v prefix is not needed sorry

**Review by pepov — APPROVED** [review]

**Pull request merged**
