### PR TITLE
add coverage reporting for e2e tests

### LINKED ISSUE #1533: CI: add e2e test coverage report
**Is your feature request related to a problem? Please describe.**
It would be great to have the e2e tests coverage reports as they cover much a bigger part of the code base compared to unit tests. 
Some resources:

- https://go.dev/blog/integration-test-coverage
- https://go.dev/testing/coverage/

**Describe the solution you'd like**
Build the binary with `-cover` flag, run the binary with `GOCOVERDIR=some_coverage_dir` and at the end of the e2e test run merge those files to have a nice (hopefully) high overall coverage report.

**Describe alternatives you've considered**
I do not think there is any.

**Additional context**

The tricky part is getting those reports, because currently the CI runs the e2e tests using kind. As [mentioned in the docs](https://go.dev/testing/coverage/#panicprof) graceful shutdown is needed for the program to write it's report, so a simple `kubectl cp` command might not be enough (not tested, just a theory).

### PR DESCRIPTION
**Pull request by nak0f**
fixes  #1533

### CODE REVIEW

**Comment by nak0f** [comment]
This works in my local but didn't work in Github CI. Most likely, [kind host volume mounts](https://kind.sigs.k8s.io/docs/user/configuration/#extra-mounts) don't work in here. I will try to solve this with something else.

**Comment by nak0f** [comment]
Below you can see output from the fist successful [run](https://github.com/kube-logging/logging-operator/actions/runs/8820557729/job/24214533653?pr=1726):
```
--- E2E test coverage report
go tool covdata percent -i=/home/runner/work/logging-operator/logging-operator/build/_test_coverage/covdatafiles
	github.com/kube-logging/logging-operator		coverage: 57.7% of statements
	github.com/kube-logging/logging-operator/controllers/extensions		coverage: 5.9% of statements
	github.com/kube-logging/logging-operator/controllers/logging		coverage: 75.5% of statements
	github.com/kube-logging/logging-operator/pkg/compression		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/mirror		coverage: 65.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources		coverage: 100.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/annotation		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/configcheck		coverage: 76.7% of statements
	github.com/kube-logging/logging-operator/pkg/resources/eventtailer		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/fluentbit		coverage: 60.5% of statements
	github.com/kube-logging/logging-operator/pkg/resources/fluentd		coverage: 62.7% of statements
	github.com/kube-logging/logging-operator/pkg/resources/hosttailer		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/kubetool		coverage: 25.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/loggingdataprovider			github.com/kube-logging/logging-operator/pkg/resources/model		coverage: 68.3% of statements
	github.com/kube-logging/logging-operator/pkg/resources/nodeagent		coverage: 0.4% of statements
	github.com/kube-logging/logging-operator/pkg/resources/prometheus-operator		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/syslogng		coverage: 57.1% of statements
	github.com/kube-logging/logging-operator/pkg/resources/templates		coverage: 75.0% of statements
	github.com/kube-logging/logging-operator/pkg/resources/volumepath		coverage: 0.0% of statements
	github.com/kube-logging/logging-operator/pkg/webhook/podhandler		coverage: 0.0% of statements
```

**Comment by pepov** [comment]
@nak0f this looks good, do you think this is now ready for review?

**Review by pepov — APPROVED** [review]

**Comment by nak0f** [comment]
> @nak0f this looks good, do you think this is now ready for review?

I was thinking of merging these with unit test coverage. Maybe adding a CI step with a coverage check. Is it better to keep this separate and leave these for future?

**Comment by pepov** [comment]
whatever works for you, no hurries

**Comment by nak0f** [comment]
After taking a look, I think it is better to keep E2E test coverage separated as CI and E2E tests run in different Workflows.

Please leave your review when available.

**Review by OverOrion — APPROVED** [review]
Works as intended, thank you!

```
--- E2E test coverage report
        github.com/kube-logging/logging-operator                coverage: 56.9% of statements
        github.com/kube-logging/logging-operator/controllers/extensions         coverage: 5.9% of statements
        github.com/kube-logging/logging-operator/controllers/logging            coverage: 75.5% of statements
        github.com/kube-logging/logging-operator/pkg/compression                coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/mirror             coverage: 65.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources          coverage: 100.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/annotation               coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/configcheck              coverage: 76.7% of statements
        github.com/kube-logging/logging-operator/pkg/resources/eventtailer              coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/fluentbit                coverage: 59.4% of statements
        github.com/kube-logging/logging-operator/pkg/resources/fluentd          coverage: 61.4% of statements
        github.com/kube-logging/logging-operator/pkg/resources/hosttailer               coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/kubetool         coverage: 25.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/loggingdataprovider                      github.com/kube-logging/logging-operator/pkg/resources/model           coverage: 68.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/nodeagent                coverage: 0.4% of statements
        github.com/kube-logging/logging-operator/pkg/resources/prometheus-operator              coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/syslogng         coverage: 58.2% of statements
        github.com/kube-logging/logging-operator/pkg/resources/templates                coverage: 75.0% of statements
        github.com/kube-logging/logging-operator/pkg/resources/volumepath               coverage: 0.0% of statements
        github.com/kube-logging/logging-operator/pkg/webhook/podhandler         coverage: 0.0% of statements
```

**Pull request merged**
