### PR TITLE
feat(charts,logging-operator): add possibility to deploy extra manife…

### PR DESCRIPTION
**Pull request by sebastiangaiser**
…sts to Helm chart

### CODE REVIEW

**Comment by sebastiangaiser** [comment]
@pepov maybe you can include that in the upcomming release tomorrow :D

**Comment by pepov** [comment]
@sebastiangaiser what is the usecase for this? what is the reason against creating an umbrella chart and putting extra resources there?

**Comment by sebastiangaiser** [comment]
My use case are the PrometheusRules from [here](https://github.com/kube-logging/logging-operator/issues/1749)

**Comment by pepov** [comment]
I meant that you can create a high level chart, add you prometheus resources and add the logging operator as a dependency into that. I haven't really seen this extra resources as a practice this is why I ask.

The term comes from here: https://helm.sh/docs/howto/charts_tips_and_tricks/#complex-charts-with-many-dependencies

**Comment by pepov** [comment]
I've found a few usage for this in the most popular charts, ok for me

**Review by pepov — APPROVED** [review]

**Review by OverOrion — APPROVED** [review]

**Pull request merged**
